### ISSUE TITLE
Koodikatselmointi #2

### ISSUE THREAD

**Issue by samhareem** [djmarsu/mittaa-aanenkorkeuden#1]
Ladattu 15.06.2016, klo 17:30

Osalle metodeista ei ole vielä ollenkaan kommentteja. Olisi ainakin hyvä selvittää perusasiat, kuten tarkoitus, parametrit ja paluuarvo.

Myös toimintaperiaatetta avaavia kommentteja olisi koodissa voinut olla enemmän. Vaikka koodi onkin hyvin seurattavaa, jäävät joidenkin metodien tarkoitukset vähän epäselväksi (esim. mitä count_zerocrossings oikeastaan tekee).

Testit näyttävät kattavilta, mutta eivät taida ollenkaan testata virhetilanteita (epäkelpo tiedosto yms.). Vaikka koodin virhesieppaus onkin hyvin tehty, olisi tämän varmistus mielestäni hyvä lisätä testeihin.

Jos nyt jotain vielä voin nillittää niin commitit voisivat olla kuvaavia. Mutta se on nyt nillitystä, hyvältä näyttää tuo koodi.

**Comment by djmarsu** [comment]
ok kiitos :D Millasia niitten SItoutumisviestejen (commit message) pitäs olla? :D

**Comment by samhareem** [comment]
Vois ehkä mainita tarkemmin mihin metodeihin, luokkiin yms. on tehnyt muutoksia. Mutta kuten sanoin, nillitän vaan nillittääkseni, eipä ne mullakaan ole sen kummempia :D

**Comment by djmarsu** [comment]
:D illan jatkoja
